apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cloudrest-deploy
spec:
  selector:
    matchLabels:
      app: cloudrest-app
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudrest-app
    spec:
      serviceAccountName: cloudrest-tasks-sa
      automountServiceAccountToken: true
      volumes:
      - name: google-cloud-key
        secret:
          secretName: tasks-gcloud-key
      containers:
      - name: mongodb
        image: mongo:4
      - name: cloudrest
        image: gcr.io/bitbox-cloud-stage/cloudrest:latest
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
        - containerPort: 5000
