apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudrest-tasks-sa
automountServiceAccountToken: false
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cloudrest-tasks-role
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudrest-tasks-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cloudrest-tasks-sa
  namespace: default
roleRef:
  kind: Role
  name: cloudrest-tasks-role
  apiGroup: rbac.authorization.k8s.io
